blank_issues_enabled: true
contact_links:
  - name: Feature request âœ¨
    url: https://github.com/owid/covid-19-data/discussions/categories/ideas
    about: Are we missing something? Start an "Ideas" discussion.
  - name: General question ðŸ’¬
    url: https://github.com/owid/covid-19-data/discussions/categories/general
    about: Not sure where to post your issue? Start a "General" discussion. 
  - name: Our development documentation ðŸ“š
    url: https://covid-docs.ourworldindata.org/
    about: Refer to our developer documentation to know more about how we maintain this project. 
