countries:
  - org_name: "Afghanistan"
    owid_name: "Afghanistan"
  # - org_name: "Bahrain"
  #   owid_name: "Bahrain"
  # - org_name: "Djibouti"
  #   owid_name: "Djibouti"
  # - org_name: "Egypt"
  #   owid_name: "Egypt"
  # - org_name: "Iran (Islamic Republic of)"
  #   owid_name: "Iran"
  - org_name: "Iraq"
    owid_name: "Iraq"
  # - org_name: "Jordan"
  #   owid_name: "Jordan"
  - org_name: "Kuwait"
    owid_name: "Kuwait"
  # - org_name: "Lebanon"
  #   owid_name: "Lebanon"
  # - org_name: "Libya"
  #   owid_name: "Libya"
  # - org_name: "Morocco"
  #   owid_name: "Morocco"
  - org_name: "Occupied Palestinian territory"
    owid_name: "Palestine"
  - org_name: "Oman"
    owid_name: "Oman"
  # - org_name: "Pakistan"
  #   owid_name: "Pakistan"
  # - org_name: "Qatar"
  #   owid_name: "Qatar"
  # - org_name: "Saudi Arabia"
  #   owid_name: "Saudi Arabia"
  # - org_name: "Somalia"
  #   owid_name: "Somalia"
  # - org_name: "Sudan"
  #   owid_name: "Sudan"
  - org_name: "Syrian Arab Republic"
    owid_name: "Syria"
  # - org_name: "Tunisia"
  #   owid_name: "Tunisia"
  # - org_name: "United Arab Emirates"
  #   owid_name: "United Arab Emirates"
  - org_name: "Yemen"
    owid_name: "Yemen"
  