countries:
  - org_name: "Anguilla"
    owid_name: "Anguilla"
  - org_name: "Bahamas"
    owid_name: "Bahamas"
  - org_name: "Belize"
    owid_name: "Belize"
  - org_name: "Bermuda"
    owid_name: "Bermuda"
  - org_name: "Dominica"
    owid_name: "Dominica"
  - org_name: "Grenada"
    owid_name: "Grenada"
  - org_name: "Guatemala"
    owid_name: "Guatemala"
  - org_name: "Guyana"
    owid_name: "Guyana"
  - org_name: "Honduras"
    owid_name: "Honduras"
  - org_name: "Nicaragua"
    owid_name: "Nicaragua"
  # - org_name: "Panama"
  #   owid_name: "Panama"
  - org_name: "St Lucia"
    owid_name: "Saint Lucia"
  - org_name: "Colombia"
    owid_name: "Colombia"
  - org_name: "Panama"
    owid_name: "Panama"
  - org_name: "Paraguay"
    owid_name: "Paraguay"
  - org_name: "Venezuela"
    owid_name: "Venezuela"
  - org_name: "St Kitts & Nevis"
    owid_name: "Saint Kitts and Nevis"
