execution:
  parallel: True
  njobs: -2

pipeline:

  vaccinations:
    get:
      countries:
      skip_countries:
        - Gabon
        - Morocco # Government data doesn't differentiate 1- and 2-dose vaccines so we use WHO instead
        - North Macedonia
        - South Africa
        - africacdc
        - Austria
        - Guatemala
        # - Faeroe Islands
    process:
      skip_complete:
        - Pitcairn
      skip_monotonic_check:
      skip_anomaly_check:
        Algeria:
          - date: 2022-02-17
            metrics: total_boosters
        Australia:
          - date: 2021-05-23
            metrics: people_vaccinated
        Bahrain:
          - date: 2021-03-06
            metrics: total_vaccinations
        Bolivia:
          - date: 2021-03-06
            metrics: people_vaccinated
        Brazil:
          - date: 2021-01-21
            metrics: 
            - total_vaccinations
            - people_vaccinated
        Bulgaria:
          - date: 2021-12-14
            metrics: total_boosters
        Luxembourg:
          - date: 2022-02-13
            metrics: people_fully_vaccinated
        Nigeria:
          - date: 2021-06-15
            metrics: people_fully_vaccinated
        United States:
          - date: 2020-12-16
            metrics: people_vaccinated
    generate:
    export:

  testing:
    get:
      countries: 
      skip_countries:
        - Benin #the source is n longer updating
        - Kazakhstan
    process:
    generate:
    export:
